export const HOLD_SHORTCUT = ['Control', 'Shift'] as const
export const HOLD_SHORTCUT_LABEL = '⌃ Control + ⇧ Shift'

export const IPC_CHANNELS = {
  OVERLAY_STATE: 'overlay:hold-state',
  OVERLAY_MODE: 'overlay:mode',
  OVERLAY_ERROR: 'overlay:error',
  SCREENSHOT_CAPTURE: 'screenshot:capture',
  SCREENSHOT_DISCARD: 'screenshot:discard',
  SELECTION_EXPORT: 'selection:export',
  SIDECAR_STATUS: 'sidecar:status',
  SETTINGS_GET: 'settings:get',
  SETTINGS_UPDATE: 'settings:update',
  SETTINGS_CHECK_OLLAMA: 'settings:check-ollama',
  SETTINGS_PROBE_VISION: 'settings:probe-vision',
  SETTINGS_RELOAD_YOUTU_AGENT: 'settings:reload-youtu',
  SETTINGS_OPEN: 'settings:open',
  APP_QUIT: 'app:quit',
  LOGGER_MESSAGE: 'logger:message',
  POINTER_SCALE: 'pointer:scale',
  SESSION_START: 'session:start',
  SESSION_BOOTSTRAP: 'session:bootstrap',
  SESSION_UPDATE: 'session:update',
  SESSION_REVEAL: 'session:reveal',
  SESSION_RESIZE: 'session:resize',
  CHAT_START: 'chat:start',
  CHAT_BOOTSTRAP: 'chat:bootstrap',
  CHAT_UPDATE: 'chat:update',
  CHAT_RESIZE: 'chat:resize',
  REPORT_START: 'report:start',
  REPORT_BOOTSTRAP: 'report:bootstrap',
  REPORT_SUBMIT: 'report:submit',
  REPORT_AUTO_SUBMIT: 'report:auto-submit',
  GUIDE_SUPPRESS: 'guide:suppress',
} as const
